version: 2.1

commands:
  cached-checkout:
      description: "checkout with caching"
      steps:
        - restore_cache:
            name: Restore Git Cache
            keys:
              - git-{{ .Branch }}-{{ .Revision }}
              - git-{{ .Branch }}-
              - git-
        - checkout:
            name: Check Out Code
        - run:
            name: Fetch from Git
            command: |
              git fetch origin
              git config user.name 'CircleCI Automated Commit'
              git config user.email 'github@raccoonfink.com'
        - save_cache:
            name: Save Git Cache
            key: git-{{ .Branch }}-{{ .Revision }}
            paths:
              - ".git"
  cached-npm-install:
      description: run "npm install", updating cache
      steps:
        - restore_cache:
            name: Restore Package Cache
            keys:
              - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
              - npm-packages-{{ .Branch }}
              - npm-packages-
        - run:
            name: Install Node Dependencies
            command: npm --prefer-offline --no-progress ci
        - save_cache:
            name: Save Package Cache
            key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
            paths:
              - node_modules/

jobs:
  run-tests:
      docker:
        - image: circleci/node:12-browsers
          environment:
            TZ: "America/New_York"
      steps:
        - cached-checkout
        - cached-npm-install
        - run:
            name: Run Link Check
            command: npm --prefer-offline --no-progress run lint
        - run:
            name: Run Build
            command: npm --prefer-offline --no-progress run build

workflows:
  run-tests:
    jobs:
      - run-tests
